name: Container Security

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  container-security:
    name: Build and Scan Container
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------------
      # Node.js
      # -------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Verify Node
        run: |
          node --version
          npm --version

      # -------------------------------
      # Docker Build
      # -------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t node-container-security:${{ github.sha }} \
            .

      # -------------------------------
      # Install Trivy
      # -------------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Verify Trivy
        run: |
          trivy --version

      # -------------------------------
      # Container vulnerability scan
      # -------------------------------
      - name: Trivy image scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            node-container-security:${{ github.sha }}

      # -------------------------------
      # Filesystem security scan
      # -------------------------------
      - name: Trivy filesystem scan
        run: |
          trivy fs . \
            --scanners vuln,secret,misconfig \
            --severity HIGH,CRITICAL \
            --exit-code 1