name: Container Security

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  container-security:
    name: Build and Scan Container
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------------
      # Node.js
      # -------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Verify Node
        run: |
          node --version
          npm --version
      - name: Generate dependencies
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            -w /app \
            node:24-bookworm-slim \
            npm install
            
      - name: Install and inspect dependencies
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            -w /app \
            node:24-bookworm-slim \
            sh -c '
              npm install &&
              echo "===== TAR =====" &&
              npm explain tar || true &&
              echo "===== BRACE-EXPANSION =====" &&
              npm explain brace-expansion || true &&
              echo "===== UNDICI =====" &&
              npm explain undici || true &&
              echo "===== IP-ADDRESS =====" &&
              npm explain ip-address || true
            '
      # -------------------------------
      # Docker Build
      # -------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t container-security:${{ github.sha }} \
            .
      - name: Verify container runs as non-root
        run: |
          docker run -d --name security-test \
            container-security:${{ github.sha }}

          echo "Container configured user:"
          docker inspect security-test --format='{{.Config.User}}'

          echo "Actual container user:"
          docker exec security-test whoami

          echo "Container UID:"
          docker exec security-test id

          docker rm -f security-test
      
      # -------------------------------
      # Verify packages inside image
      # -------------------------------
      # - name: Verify packages inside image
      #   run: |
      #     docker run --rm \
      #       node-container-security:${{ github.sha }} \
      #       node -e "
      #         console.log(require('brace-expansion/package.json').version);
      #         console.log(require('ip-address/package.json').version);
      #         console.log(require('tar/package.json').version);
      #         console.log(require('undici/package.json').version);
      #       "
  
      # -------------------------------
      # Install Trivy
      # -------------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Verify Trivy
        run: |
          trivy --version
     
      # -------------------------------
      # Container vulnerability scan
      # -------------------------------
      - name: Trivy image scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            container-security:${{ github.sha }}

      # -------------------------------
      # Filesystem security scan
      # -------------------------------
      - name: Trivy filesystem scan
        run: |
          trivy fs . \
            --scanners vuln,secret,misconfig \
            --severity HIGH,CRITICAL \
            --exit-code 0
      
     # -------------------------------
      # SBOM
      # -------------------------------
      - name: Generate SBOM
        run: |
          trivy image \
            --format cyclonedx \
            --output sbom.json \
            container-security:${{ github.sha }}

      - name: Scan SBOM
        run: |
          trivy sbom \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: container-sbom
          path: sbom.json




