name: Container Security

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  container-security:
    name: Build and Scan Container
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Node is only needed to build/test the application.
      # Docker will actually install the Node dependencies.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run application test
        run: |
          node --version
          npm --version

      - name: Build Docker image
        run: |
          docker build \
            -t node-container-security:${{ github.sha }} \
            .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: node-container-security:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          severity: HIGH,CRITICAL
          exit-code: 1